### ISSUE TITLE
Docker CentOS 7 version `GLIBC_2.18' not found (required by py-spy)

### ISSUE THREAD

**Issue by yutkin** [benfred/py-spy#16] opened 2018-09-07 08:11 UTC
Tried to run in Docker (CentOS 7 image) and got this:
`py-spy: /lib64/libc.so.6: version "GLIBC_2.18" not found (required by py-spy)`

**Comment by JackLeo** [comment] 2018-09-07 14:26
this is an issue in non docker centos 7 as well. The latest provided version is `glibc-2.17-222.el7.x86_64`. Does this project actually depend on the `2.18`?

**Comment by benfred** [comment] 2018-09-08 00:47
We technically only need glibc 2.15 (for the process_vm_readv call). It seems like it's possible to distribute with a statically linked version of this though which will be a better solution.

Closing this as a duplicate of https://github.com/benfred/py-spy/issues/5,

**Closed** 2018-09-08 00:47 UTC
Labels: duplicate
