### ISSUE TITLE
stack traces in flamegraph appear without callers

### ISSUE THREAD

**Issue by Pike** [benfred/py-spy#56] opened 2018-11-13 00:02 UTC
I'm running some profiles with a flame graph, and there are top-level entry points in my flame graph that are clearly not top-level entry points.

For example, the return statement of a function inside a function, https://github.com/projectfluent/python-fluent/blob/6f3b911f88c821865a80c36fc6622d0a8e0e12c9/fluent/syntax/ast.py#L63, is a top-level section in the flame graph.

Stack traces are pretty deep, but they're far from 4k, which is the only thing I found indicating stack trace depth limits.

I'm seeing this on python 2.7.10 and 3.6.5

**Comment by benfred** [comment] 2018-11-16 18:06
I think I've managed to replicate this - it seems to mainly happen with deep-ish callstacks, where the python functions aren't taking any significant time. 

It'd be great to figure out a way to discard these callstacks so we can keep the profiler from blocking the python program - but I can't see any way of doing it right now (just with a higher error rate during sampling). The problem is that the end of the a legitimate call stack is indicated by a null pointer on the 'next' frame - which is the same thing that is happening here.  Going to see if pausing the python program with ptrace etc resolves this

**Comment by benfred** [comment] 2018-12-05 06:06
This commit seems to fix: https://github.com/benfred/py-spy/pull/65/commits/e25656c97ad5d32f6dce437c7075c6e440613f35

**Comment by benfred** [comment] 2018-12-06 05:57
fixed in v0.1.9

**Closed by benfred** 2018-12-06 05:57 UTC

**Comment by Pike** [comment] 2018-12-06 08:44
Sweet, thanks. Updated and my use-case seems to be working fine now.

Also, the slow-down is just 3% in the case I tried.
