### ISSUE TITLE
zsh: command not found: py-spy (macOS 10.15.4)

### ISSUE THREAD

**Issue by hoenickf** [benfred/py-spy#236] opened 2020-05-04 10:47 UTC
Hi, 
I installed py-spy but can not run it afterwards.
Install command: pip install py-spy
When I type
py-spy top --pid xxxx
I get: 
zsh: command not found: py-spy

**Comment by benfred** [comment] 2020-05-04 16:54
What does ``` pip show py-spy -f``` show after installing?   You should see the install location (like ```/Users/ben/anaconda3/lib/python3.7/site-packages```) and the location of the binary relative to that path (```  ../../../bin/py-spy```) in the output there.

**Comment by krasatos** [comment] 2020-05-13 22:27
> What does ` pip show py-spy -f` show after installing? You should see the install location (like `/Users/ben/anaconda3/lib/python3.7/site-packages`) and the location of the binary relative to that path (` ../../../bin/py-spy`) in the output there.

Having the same issue, and i cant quite understand your explanation.
The output of ` pip show py-spy -f` is as you said, what should i do next?
Excuse my ignorance ofcourse, and thank you in advance.

**Comment by benfred** [comment] 2020-05-13 22:35
I'm guessing either the py-spy binary doesn't exist, isn't executable, or the bin directory isn't in your path.

If the py-spy binary is showing up in pip show, first make sure it exists by going
```
ls -lash <INSTALL_LOCATION_FROM_PIP_SHOW><BINARY_LOCATION_FROM_PIP_SHOW>
```
(getting the path by concat'ing the two paths from pip show)

If the py-spy binary exists, try running using the full path. If you can run using the full path, make sure the directory is in your PATH =)

**Comment by krasatos** [comment] 2020-05-13 22:44
@benfred , Thanks for your super-fast reply. 
` sudo /home/username/.local/bin/py-spy record -o profile.svg --pid 12053` Worked ok!

**Comment by benfred** [comment] 2020-05-14 01:43
Great! 

Going to close this issue - its seems like the problem is that the python bin directory isn't in the path (possibly just not in the path of the root user, fwiw ```sudo env "PATH=$PATH"  py-spy  ...```

**Closed by benfred** 2020-05-14 01:43 UTC

**Comment by milindvdamle** [comment] 2020-09-10 18:59
I ran into this same issue on macOS Catalina (10.15.6). It looks like the installer didn't create a symlink to the py-spy binary. In my case, adding a symlink in /usr/local/bin to point to the actual location fixed the issue, so perhaps it should be part of the installer?

$ sudo ln -s /Library/Frameworks/Python.framework/Versions/3.7/bin/py-spy /usr/local/bin/py-spy

Thanks
Milind
