### ISSUE TITLE
"Failed to find a python interpreter in the .data section"

### ISSUE THREAD

**Issue by xiewendan** [benfred/py-spy#593] opened 2023-06-15 03:22 UTC
I use py-spy to run py by python3.11.3 on windows

`
py-spy record -o profile.svg -- python -c "import time;time.sleep(100)"
Error: Failed to find a python interpreter in the .data section
`

operating system: windows
py-spy version: 0.3.14
python version: 3.11.3

**Comment by akjroller** [comment] 2023-07-03 03:15
I think the issue is that py-spy only supports Python versions up to 3.9. I tried it as well using 3.11.4 and got the same error.

**Comment by alispa** [comment] 2023-12-17 21:14
Thanks @akjroller for at least the temporary solution.
I confirm that on python 3.9 it worked and on python 3.10 not. (Windows)

**Comment by burrowsa** [comment] 2024-02-01 12:04
I am also seeing this issue. If the program I want to profile is running in python 3.10 then I can't profile it with py-spy, but I can profile the same program running under python 3.7

![image](https://github.com/benfred/py-spy/assets/1609099/e226d167-3312-4c27-be13-94628215f8bd)
![image](https://github.com/benfred/py-spy/assets/1609099/c298ebe7-cea7-4d14-9680-e1555cbc3b7a)

**Comment by aakash-sahai** [comment] 2024-02-29 13:58
This is a duplicate of https://github.com/benfred/py-spy/issues/643. Some solutions/workarounds can be found posted there.

**Comment by fleimgruber** [comment] 2024-02-29 14:48
@aakash-sahai thanks for mentioning! But measured by creation time, #643 is a duplicate of this issue, also mentioned in https://github.com/benfred/py-spy/issues/643#issuecomment-1859271016.

**Comment by akhramov** [comment] 2024-07-13 23:28
https://github.com/benfred/py-spy/pull/672 this __might__ fix the problem. I need to test on an amd64 machine first.

**Comment by benfred** [comment] 2024-11-01 22:29
I think this should be fixed in the 0.4 release. Can you try it out and let me know?

If this is still not working please re-open the issue

**Closed by benfred** 2024-11-01 22:29 UTC
