### ISSUE TITLE
Support for Python 3.12

### ISSUE THREAD

**Issue by kefrens** [benfred/py-spy#670] opened 2024-06-14 13:38 UTC
Hi
I'm trying to install py-spy to troubleshoot HomeAssistant but I am having the following message when trying to dump on HA PID
Error: Unsupported version of Python: 3.12.0

Is there any plan to make it working? Is there any workaround?

**Comment by ptmcg** [comment] 2024-06-20 14:00
Duplicate of #661 which is a duplicate of #633

**Comment by zanieb** [comment] 2024-10-15 01:55
Closed by https://github.com/benfred/py-spy/pull/642

**Closed** 2024-10-30 22:29 UTC
